
name: Test
on: 
  push:
    branches:
      - '*'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '8' ]
    name: Node ${{ matrix.node }} test
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install
      - name: Run test
        run: yarn test
